### ISSUE TITLE
Undistorted point cloud from wide FoV

### ISSUE THREAD

**Issue by zachary-dpt** [design-io/ofxOrbbec#2]
I've been working on a software that perform blob detection using the point clouds from Kinect and I'm working on updating it to work with the latest Orbbec cameras (Femto Bolt and Femto Mega)

I started by using this addon to get the point cloud from the wide field of view (512 x 512) and when I do, the point cloud is distorted and not properly aligned with real world coordinates. 
(screen capture from the OrbbecViewer but it's the same in ofx)
![image](https://github.com/design-io/ofxOrbbec/assets/71455257/85172e07-158f-4362-980f-2fa0f6c9fde9)

To remedy that, Orbbec has a mode to align the depth points with the color camera view (D2C). However, the points that are not within the camera view are discarded, rendering the use of the wide FoV texture useless because a big part of the data is lost.
(screen capture from the OrbbecViewer but it's the same in ofx)
![image](https://github.com/design-io/ofxOrbbec/assets/71455257/5b5472ff-dd8c-4d2d-95ae-953a23b0a0df)

I was wondering if you've seen a way to undistort the point cloud based on world coordinates, like the Azure Kinect SDK had, and not based on the RGB camera view? Should I just use the K4A wrapper in openframeworks instead of the Orbbec SDK?
(screen capture from the OrbbecSDK-K4A-Wrapper version of the Kinect viewer)
![image](https://github.com/design-io/ofxOrbbec/assets/71455257/c8fa89eb-9d44-4423-91fc-3b69d50bc45f)

Thank you!

**Comment by ofTheo** [comment]
@zacharylr  I think what you want is to have a non aligned point cloud - ie: setAlignMode(ALIGN_DISABLE) 

Are you enabling pointCloudRGB in the ofxOrbbecCamera class as that makes it aligned. 
https://github.com/design-io/ofxOrbbec/blob/main/src/ofxOrbbecCamera.cpp#L193-L197

**Comment by zachary-dpt** [comment]
Thanks for your answer and the addon @ofTheo !

The first image in my post is the result of _setAlignMode(ALIGN_DISABLE)_. The resulting point cloud is distorted because of the wide field of view of the lens. The OrbbecSDK doesn't do any undistortion operation.

The second image is the result of  _setAlignMode(ALIGN_D2C_HW_MODE)_. The resulting point cloud is somewhat undistorted but the alignment with the RGB camera discard a lot of the points because they are not part of the RGB cam field of view.

We are currently trying to implement some undistort functions on the raw _ALIGN_DISABLE_ point cloud (in WFOV) to be able to use the full data from it. We raised the issue on the OrbbecSDK github but it doesn't seem to be something they want to integrate in the SDK, even though it was part of the original AzureKinectSDK.

We'll let you know how it goes. Thank you!

**Comment by ofTheo** [comment]
Oh wow - thanks @zacharylr. 

So does that mean the point cloud is not accurate in terms of XYZ position in mm unless it is set to use ALIGN_D2C_HW_MODE? 

That sort of makes it useless and def not a 1:1 replacement for the Kinect. 

Do you know if that only affects WFOV or is it both views? 

I'm going to add my comments to that issue: 
https://github.com/orbbec/OrbbecSDK/issues/39

**Comment by ofTheo** [comment]
@zacharylr - undistorted point clouds now working as of [current master](https://github.com/design-io/ofxOrbbec/commit/26757f4def64f75cb8cde83db7e610b99ae45b16#diff-fbafc5c1167a89b2878b8b151f21c927fc1539343435fba3e064826fcbc31afbR586)
